name: "AI-Driven DevSecOps Framework"
description: "Reusable DevSecOps action for C/C++ static analysis"

inputs:
  scan-path:
    description: "Path to scan in the target repository"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install SAST tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang clang-tools

    - name: Create reports folder
      shell: bash
      run: |
        mkdir -p reports
        mkdir -p reports/clang-report

    - name: Run Cppcheck static analysis
      shell: bash
      run: |
        cppcheck --enable=all --inconclusive --xml "${{ inputs.scan-path }}" 2> reports/cppcheck-report.xml || true

    - name: Run Clang Static Analyzer
      shell: bash
      run: |
        FILES=$(find "${{ inputs.scan-path }}" \( -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" \))

        echo "Files found for Clang analysis:"
        echo "$FILES"

        if [ -z "$FILES" ]; then
          echo "No C/C++ files found for Clang analysis." | tee reports/clang-output.txt
        else
          scan-build --status-bugs -o reports/clang-report clang -std=gnu89 -fsyntax-only $FILES > reports/clang-output.txt 2>&1 || true
        fi

    - name: Show Cppcheck XML report
      shell: bash
      run: |
        echo "===== Cppcheck XML Report ====="
        cat reports/cppcheck-report.xml || true

    - name: List Clang report files
      shell: bash
      run: |
        echo "===== Clang Static Analyzer Report Files ====="
        find reports/clang-report -type f || true

    - name: Run alert prioritisation (ML 2 baseline)
      shell: bash
      run: |
        python3 "$GITHUB_ACTION_PATH/ml/alert_prioritizer.py"

    - name: Upload Cppcheck XML report
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-xml-report
        path: reports/cppcheck-report.xml

    - name: Upload Clang analyzer console output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: clang-console-output
        path: reports/clang-output.txt
        if-no-files-found: ignore

    - name: Upload Clang Static Analyzer report folder
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: clang-static-analyzer-report
        path: reports/clang-report
        if-no-files-found: ignore

    - name: Upload prioritised alerts report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: prioritised-alerts
        path: reports/prioritised-alerts.csv
        if-no-files-found: ignore