name: AI-Driven DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run static analysis (Cppcheck)
        run: |
          cppcheck --enable=all --inconclusive vulnerable_code/ 2> reports/cppcheck-report.txt || true

      - name: Show Cppcheck report
        run: |
          echo "===== Cppcheck Report ====="
          cat reports/cppcheck-report.txt || true